// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thiccdal.Data;

#nullable disable

namespace Thiccdal.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Thiccdal.Data.Models.BotCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HandlerType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Trigger")
                        .IsUnique();

                    b.ToTable("BotCommands");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlatformEventId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlatformUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformEventId")
                        .IsUnique();

                    b.HasIndex("PlatformUserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.ChatterMemoryReset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ResetAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Channel", "PlatformUserId", "ResetAt");

                    b.ToTable("ChatterMemoryResets");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.ChecklistSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("ChecklistSessions");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.ChecklistSessionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ChecklistSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistSessionId", "ItemId")
                        .IsUnique();

                    b.ToTable("ChecklistSessionItems");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.CustomChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomChecklistItems");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.PlatformEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Platform");

                    b.Property<string>("SourceEventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlatformEvents");

                    b.HasDiscriminator<string>("EventType").HasValue("PlatformEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Thiccdal.Data.Models.PlatformUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFollower")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscriber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriptionMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentityId");

                    b.HasIndex("Source", "PlatformUserId")
                        .IsUnique();

                    b.ToTable("PlatformUsers");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.ProactiveMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProactiveMessages");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.RestreamConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrbSlatePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordingOutputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartWithHost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RestreamConfigurations");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.RestreamDestinationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformName")
                        .IsUnique();

                    b.ToTable("RestreamDestinationConfigurations");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.StreamRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Platform", "StartedAt");

                    b.ToTable("StreamRecordings");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.TwitchTargetChannelConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BroadcasterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetChannel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TwitchTargetChannels");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.TwitchToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TwitchTokens");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.UserIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserIdentities");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.UserIdentitySuggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstPlatformUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SecondPlatformUserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SecondPlatformUserId");

                    b.HasIndex("FirstPlatformUserId", "SecondPlatformUserId")
                        .IsUnique();

                    b.ToTable("UserIdentitySuggestions");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.YouTubeToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YouTubeTokens");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.FollowEvent", b =>
                {
                    b.HasBaseType("Thiccdal.Data.Models.PlatformEvent");

                    b.HasDiscriminator().HasValue("FollowEvent");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.MembershipEvent", b =>
                {
                    b.HasBaseType("Thiccdal.Data.Models.PlatformEvent");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MonthCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("MembershipEvent");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.RaidEvent", b =>
                {
                    b.HasBaseType("Thiccdal.Data.Models.PlatformEvent");

                    b.Property<string>("RaidingChannel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("RaidEvent");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.RedeemEvent", b =>
                {
                    b.HasBaseType("Thiccdal.Data.Models.PlatformEvent");

                    b.Property<string>("RewardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInput")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("RedeemEvent");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.SubscribeEvent", b =>
                {
                    b.HasBaseType("Thiccdal.Data.Models.PlatformEvent");

                    b.Property<long?>("GifterPlatformUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGift")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("GifterPlatformUserId");

                    b.HasDiscriminator().HasValue("SubscribeEvent");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.SuperChatEvent", b =>
                {
                    b.HasBaseType("Thiccdal.Data.Models.PlatformEvent");

                    b.Property<long>("AmountMicros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserComment")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SuperChatEvent");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("Thiccdal.Data.Models.PlatformEvent", "PlatformEvent")
                        .WithOne()
                        .HasForeignKey("Thiccdal.Data.Models.ChatMessage", "PlatformEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thiccdal.Data.Models.PlatformUser", "PlatformUser")
                        .WithMany("ChatMessages")
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlatformEvent");

                    b.Navigation("PlatformUser");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.ChecklistSessionItem", b =>
                {
                    b.HasOne("Thiccdal.Data.Models.ChecklistSession", "ChecklistSession")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistSession");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.PlatformUser", b =>
                {
                    b.HasOne("Thiccdal.Data.Models.UserIdentity", "UserIdentity")
                        .WithMany("PlatformUsers")
                        .HasForeignKey("UserIdentityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserIdentity");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.UserIdentitySuggestion", b =>
                {
                    b.HasOne("Thiccdal.Data.Models.PlatformUser", "FirstPlatformUser")
                        .WithMany()
                        .HasForeignKey("FirstPlatformUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thiccdal.Data.Models.PlatformUser", "SecondPlatformUser")
                        .WithMany()
                        .HasForeignKey("SecondPlatformUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstPlatformUser");

                    b.Navigation("SecondPlatformUser");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.SubscribeEvent", b =>
                {
                    b.HasOne("Thiccdal.Data.Models.PlatformUser", "GifterPlatformUser")
                        .WithMany()
                        .HasForeignKey("GifterPlatformUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GifterPlatformUser");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.ChecklistSession", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.PlatformUser", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("Thiccdal.Data.Models.UserIdentity", b =>
                {
                    b.Navigation("PlatformUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
