<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>fbaec79a-dd39-4cbb-b287-5ca230167092</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Thiccdal.Modules.ChatBot\Thiccdal.Modules.ChatBot.csproj" />
    <ProjectReference Include="..\Modules\Thiccdal.Modules.Control\Thiccdal.Modules.Control.csproj" />
    <ProjectReference Include="..\Modules\Thiccdal.Modules.Overlay\Thiccdal.Modules.Overlay.csproj" />
    <ProjectReference Include="..\Modules\Thiccdal.Modules.Teleprompter\Thiccdal.Modules.Teleprompter.csproj" />
    <ProjectReference Include="..\Remote\Thiccdal.Remote.Discord\Thiccdal.Remote.Discord.csproj" />
    <ProjectReference Include="..\Remote\Thiccdal.Remote.Instagram\Thiccdal.Remote.Instagram.csproj" />
    <ProjectReference Include="..\Remote\Thiccdal.Remote.LinkedIn\Thiccdal.Remote.LinkedIn.csproj" />
    <ProjectReference Include="..\Remote\Thiccdal.Remote.TikTok\Thiccdal.Remote.TikTok.csproj" />
    <ProjectReference Include="..\Remote\Thiccdal.Remote.Twitch\Thiccdal.Remote.Twitch.csproj" />
    <ProjectReference Include="..\Remote\Thiccdal.Remote.YouTube\Thiccdal.Remote.YouTube.csproj" />
    <ProjectReference Include="..\Shared\Thiccdal.Shared.Components\Thiccdal.Shared.Components.csproj" />
    <ProjectReference Include="..\Aspire\Thiccdal.Aspire.ServiceDefaults\Thiccdal.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Thiccdal.API\Thiccdal.API.csproj" />
    <ProjectReference Include="..\Thiccdal.Infrastructure\Thiccdal.Infrastructure.csproj" />
    <ProjectReference Include="..\Thiccdal.Streaming\Thiccdal.Streaming.csproj" />
    <ProjectReference Include="..\Thiccdal.AI\Thiccdal.AI.csproj" />
  </ItemGroup>

</Project>
