<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiveStreamingServerNet" Version="0.33.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Thiccdal.Infrastructure\Thiccdal.Infrastructure.csproj" />
  </ItemGroup>

</Project>
